#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOAD_DIR="${SCRIPT_DIR}/load"
K6_SCRIPT="${K6_SCRIPT:-${LOAD_DIR}/scenarios/payment-access-progress.k6.js}"

AUTH_BASE_URL="${AUTH_BASE_URL:-http://127.0.0.1:8000}"
USERS_BASE_URL="${USERS_BASE_URL:-http://127.0.0.1:8002}"
COURSE_BASE_URL="${COURSE_BASE_URL:-http://127.0.0.1:8001}"
PAYMENTS_BASE_URL="${PAYMENTS_BASE_URL:-http://127.0.0.1:8004}"
COMMERCIAL_CATALOG_BASE_URL="${COMMERCIAL_CATALOG_BASE_URL:-http://127.0.0.1:8007}"
BONUS_BASE_URL="${BONUS_BASE_URL:-http://127.0.0.1:8006}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin12345}"
PARENT_PASSWORD="${PARENT_PASSWORD:-parent12345}"
STUDENT_PASSWORD="${STUDENT_PASSWORD:-student12345}"
SERVICE_TOKEN="${SERVICE_TOKEN:-sometokencourse}"
BONUS_SERVICE_TOKEN="${BONUS_SERVICE_TOKEN:-${SERVICE_TOKEN}}"
K6_PAYMENT_OFFER_ID="${K6_PAYMENT_OFFER_ID:-}"
K6_LEARNING_ENABLED="${K6_LEARNING_ENABLED:-1}"
K6_LEARNING_LESSON1_ID="${K6_LEARNING_LESSON1_ID:-}"
K6_LEARNING_LESSON2_ID="${K6_LEARNING_LESSON2_ID:-}"
K6_BONUS_ENABLED="${K6_BONUS_ENABLED:-0}"
K6_BONUS_AMOUNT="${K6_BONUS_AMOUNT:-30}"
K6_VUS="${K6_VUS:-5}"
K6_DURATION="${K6_DURATION:-2m}"
K6_THINK_TIME_SECONDS="${K6_THINK_TIME_SECONDS:-0.2}"
K6_USER_POOL_SIZE="${K6_USER_POOL_SIZE:-}"
K6_SETUP_TIMEOUT="${K6_SETUP_TIMEOUT:-20m}"
K6_DOCKER_IMAGE="${K6_DOCKER_IMAGE:-grafana/k6:0.49.0}"

log() {
  printf '[load-payment-access-progress] %s\n' "$*"
}

if ! command -v docker >/dev/null 2>&1; then
  log "ERROR docker is required"
  exit 1
fi

if [[ ! -f "${K6_SCRIPT}" ]]; then
  log "ERROR k6 script not found: ${K6_SCRIPT}"
  exit 1
fi

if [[ -z "${K6_PAYMENT_OFFER_ID}" ]]; then
  log "ERROR K6_PAYMENT_OFFER_ID is required"
  exit 1
fi

if [[ "${K6_LEARNING_ENABLED}" == "1" && ( -z "${K6_LEARNING_LESSON1_ID}" || -z "${K6_LEARNING_LESSON2_ID}" ) ]]; then
  log "ERROR K6_LEARNING_LESSON1_ID and K6_LEARNING_LESSON2_ID are required when K6_LEARNING_ENABLED=1"
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  log "ERROR docker daemon is not available"
  exit 1
fi

log "AUTH_BASE_URL=${AUTH_BASE_URL}"
log "USERS_BASE_URL=${USERS_BASE_URL}"
log "COURSE_BASE_URL=${COURSE_BASE_URL}"
log "PAYMENTS_BASE_URL=${PAYMENTS_BASE_URL}"
log "COMMERCIAL_CATALOG_BASE_URL=${COMMERCIAL_CATALOG_BASE_URL}"
log "BONUS_BASE_URL=${BONUS_BASE_URL}"
log "K6_PAYMENT_OFFER_ID=${K6_PAYMENT_OFFER_ID}"
log "K6_LEARNING_ENABLED=${K6_LEARNING_ENABLED}"
log "K6_VUS=${K6_VUS}"
log "K6_DURATION=${K6_DURATION}"
log "K6_THINK_TIME_SECONDS=${K6_THINK_TIME_SECONDS}"
log "K6_USER_POOL_SIZE=${K6_USER_POOL_SIZE:-auto}"
log "K6_SETUP_TIMEOUT=${K6_SETUP_TIMEOUT}"
log "K6_DOCKER_IMAGE=${K6_DOCKER_IMAGE}"
log "Using Docker host network for server-local traffic"

exec docker run --rm \
  --network host \
  -v "${LOAD_DIR}:/work/load:ro" \
  -e AUTH_BASE_URL="${AUTH_BASE_URL}" \
  -e USERS_BASE_URL="${USERS_BASE_URL}" \
  -e COURSE_BASE_URL="${COURSE_BASE_URL}" \
  -e PAYMENTS_BASE_URL="${PAYMENTS_BASE_URL}" \
  -e COMMERCIAL_CATALOG_BASE_URL="${COMMERCIAL_CATALOG_BASE_URL}" \
  -e BONUS_BASE_URL="${BONUS_BASE_URL}" \
  -e ADMIN_EMAIL="${ADMIN_EMAIL}" \
  -e ADMIN_PASSWORD="${ADMIN_PASSWORD}" \
  -e PARENT_PASSWORD="${PARENT_PASSWORD}" \
  -e STUDENT_PASSWORD="${STUDENT_PASSWORD}" \
  -e SERVICE_TOKEN="${SERVICE_TOKEN}" \
  -e BONUS_SERVICE_TOKEN="${BONUS_SERVICE_TOKEN}" \
  -e K6_PAYMENT_OFFER_ID="${K6_PAYMENT_OFFER_ID}" \
  -e K6_LEARNING_ENABLED="${K6_LEARNING_ENABLED}" \
  -e K6_LEARNING_LESSON1_ID="${K6_LEARNING_LESSON1_ID}" \
  -e K6_LEARNING_LESSON2_ID="${K6_LEARNING_LESSON2_ID}" \
  -e K6_BONUS_ENABLED="${K6_BONUS_ENABLED}" \
  -e K6_BONUS_AMOUNT="${K6_BONUS_AMOUNT}" \
  -e K6_VUS="${K6_VUS}" \
  -e K6_DURATION="${K6_DURATION}" \
  -e K6_THINK_TIME_SECONDS="${K6_THINK_TIME_SECONDS}" \
  -e K6_USER_POOL_SIZE="${K6_USER_POOL_SIZE}" \
  -e K6_SETUP_TIMEOUT="${K6_SETUP_TIMEOUT}" \
  "${K6_DOCKER_IMAGE}" \
  run /work/load/payment-access-progress.k6.js
